### ISSUE TITLE
Skin selection 

### ISSUE THREAD

**Issue by MARCOS30864** [ZalithLauncher/ZalithLauncher#192]
### Feature Description / 功能描述

A new skin selection option, there you can download any type of skin or even import it directly from the files 
![2024102219512779](https://github.com/user-attachments/assets/cd741188-9adb-4684-8be4-5be1689678b9)

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by ThatOneSheep** [comment]
Ooo I want that feature :D

**Comment by MARCOS30864** [comment]
@ThatOneSheep We need more people for him to notice. 🥹

**Comment by Ambientfish** [comment]
Fr

**Comment by ThatOneSheep** [comment]
Yea ;(

**Comment by Ambientfish** [comment]
How can we tag him

**Comment by MARCOS30864** [comment]
@gumen2258 Which?

**Comment by You-know-123** [comment]
Very good feature, please add it sometime later @MovTery

**Comment by MARCOS30864** [comment]
@MovTery

**Comment by Ambientfish** [comment]
@MovTery
