### ISSUE TITLE
ICONS IN CONTROL 

### ISSUE THREAD

**Issue by MARCOS30864** [ZalithLauncher/ZalithLauncher#227]
### Feature Description / 功能描述

A new possibility to import icons (transparent PNG/JPG ) for controls leaving them with their own styles. Same with the mouse.
![2024111010550704](https://github.com/user-attachments/assets/996bdde3-3c4c-41c4-b340-0578ee9c6e80)

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by gumen2258** [comment]
I think you can go to pojavlauncher and make this suggestion.
