### ISSUE TITLE
to show what the reason was 

### ISSUE THREAD

**Issue by Dorian12192** [ZalithLauncher/ZalithLauncher#239]
### Feature Description / 功能描述

Hello, for some updates I want you to add a new interface, that is, when the mods are not compatible, the latestlog.txt will appear, some people do not understand what they are for, others do not find out why, and others do not know how to use it, so I want you to add a new interface that only shows a text of what the reason was because the mods were not compatible, like the tlauncher, and a button to download the latestlog.txt 

### Additional Information / 其他信息

![Screenshot_20241112_185922_Gallery](https://github.com/user-attachments/assets/2161d6a4-90f5-4774-96ce-b5cc548c2e34)

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by ShoyebOP** [comment]
I guess all the modloaders do have some kind of gui for this. But by reading the logs I found out there's some sort of error preventing that screen to show and crashing the game
