### ISSUE TITLE
1.16.1 modpacks not working

### ISSUE THREAD

**Issue by AzonexShits** [ZalithLauncher/ZalithLauncher#271]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

I downloaded a speedrun modpacks specifically 1.16.1 and it's shows an error

### Log File / 日志文件

No logs

### Screenshots or Videos / 截图或视频

![Screenshot_20241123_142952_Zalith Launcher](https://github.com/user-attachments/assets/92fe095e-13a0-4448-86c8-24186479603b)

### Reproduction Steps / 复现步骤

```markdown
1.download the modpack in modrinth named speedrunpack select 1.16.1 select version4.2.1
2.select the modpack
```

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.7.4

### Selected Renderer / 选择的渲染器

Freedreno

### Device Information / 设备信息

Samsung a23 5g android 14 arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by AzonexShits** [comment]
![Uploading Screenshot_20241123_142952_Zalith Launcher.jpg…]()

**Comment by Vera-Firefly** [comment]
The module package is missing the JSON file. This is not the reason for the launcher. It can only be suggested to the module author to solve it.
