### ISSUE TITLE
language bug 

### ISSUE THREAD

**Issue by 0xL0st** [ZalithLauncher/ZalithLauncher#274]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

I can't change the game settings, I can't change the language, I can't enter the world.

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17892715/latestlog.txt)

### Screenshots or Videos / 截图或视频

![Screenshot_20241124_061935_Zalith Launcher](https://github.com/user-attachments/assets/9d9f7772-621f-42cb-ad4d-ca73ad32253f)

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.7.5

### Selected Renderer / 选择的渲染器

GL4ES

### Device Information / 设备信息

M54

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Dorian12192** [comment]
What mods do you use? that happens while the mojang logo loads

**Comment by Vera-Firefly** [comment]
Optifine is not compatible with current forge
Try replacing the optifine or forge loader
