### ISSUE TITLE
Red screen promblem

### ISSUE THREAD

**Issue by Shereneeeee** [ZalithLauncher/ZalithLauncher#275]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

![Screenshot_2024-11-24-17-36-05-223_com movtery zalithlauncher](https://github.com/user-attachments/assets/96095c07-0b62-48fc-8577-a14f6d5533f1)

### Log File / 日志文件

![Screenshot_2024-11-24-17-36-14-775_com movtery zalithlauncher](https://github.com/user-attachments/assets/e61d606c-8630-4cae-899f-676b3aaa0eb0)

### Screenshots or Videos / 截图或视频

All version get red screen promblem idk why

### Android Version / Android 版本

10

### App Version / 应用版本

1.3.7.5

### Selected Renderer / 选择的渲染器

GL4ES

### Device Information / 设备信息

Redmi note 8pro

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Mushrush825** [comment]
Me too
