### ISSUE TITLE
1.21.1 Sodium Fabric crash With LTW renderer

### ISSUE THREAD

**Issue by Zack694** [ZalithLauncher/ZalithLauncher#305]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

It crashes everytime

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17989559/latestlog.txt)

### Reproduction Steps / 复现步骤

```markdown
1. Play 1.21.1 with sodium and LTW Renderer 
2. Play a server
3. Crash
```

### Android Version / Android 版本

11

### App Version / 应用版本

1.3.7.8

### Selected Renderer / 选择的渲染器

LTW

### Device Information / 设备信息

Vivo y11 Android 11 arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Jussstrollin** [comment]
i dont know if sodium fabric or FML is supported by pojav/Zalith launcher . either it crashes on startup or doesnt render anything ingame

**Comment by Zack694** [comment]
> i dont know if sodium fabric or FML is supported by pojav/Zalith launcher . either it crashes on startup or doesnt render anything ingame
