### ISSUE TITLE
TouchController 模组支持

### ISSUE THREAD

**Issue by RedCarl** [ZalithLauncher/ZalithLauncher#324]
### Feature Description / 功能描述

现在可能为时稍早，但是想知道作者有没有打算对其进行支持，或者已经在进行中了。
https://github.com/fifth-light/TouchController

### This feature request has not been proposed before / 这个功能建议还没有人提出过

- [X] I have checked the Issues and found no similar feature request / 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by MovTery** [comment]
https://github.com/ZalithLauncher/ZalithLauncher/tree/support%2Ftouch-controller

**Comment by MovTery** [comment]
准备作为一个设置项，加入到main分支中去（）

**Comment by MovTery** [comment]
https://github.com/ZalithLauncher/ZalithLauncher/commit/d77b160008fced007cb527d68561fcca5c1ff4b7
