### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by JohnreyMartes14** [ZalithLauncher/ZalithLauncher#338]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

I just downloaded couple of mods and it's supported version i don't know why but i will send some launcher log

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/18224660/latestlog.txt)

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.9

### Selected Renderer / 选择的渲染器

LTW

### Device Information / 设备信息

Poco F5 5g, Android 14, Arm64 12/256

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Vera-Firefly** [comment]
- Install fabric-language-kotlin, version 1.11.0+kotlin.2.0.0 or later.
More details:
	 - Mod 'Zoomify' (zoomify) 2.14.2+1.21.1 requires version 1.11.0+kotlin.2.0.0 or later of fabric-language-kotlin, which is missing!
