### ISSUE TITLE
Erro código -1

### ISSUE THREAD

**Issue by DAVI30108** [ZalithLauncher/ZalithLauncher#345]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

I left the world and when I pressed to exit the launcher it gave error -1, I'm using sodium and the LTW launcher

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.9.1

### Selected Renderer / 选择的渲染器

LTW

### Device Information / 设备信息

Moto g73, Android 14, arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Vera-Firefly** [comment]
Can a log file be provided? This can help us solve the problem better
