### ISSUE TITLE
全屏无用

### ISSUE THREAD

**Issue by yuyuya090908** [ZalithLauncher/ZalithLauncher#352]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

全屏模式没有效果

### Log File / 日志文件

并没有

### Screenshots or Videos / 截图或视频

![Screenshot_20241231_150427_com movtery zalithlauncher](https://github.com/user-attachments/assets/a7886772-f6a6-47bd-a09a-a348c5734e3d)

### Android Version / Android 版本

15

### App Version / 应用版本

1.3.9.2

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

HUAWEI nova 5T

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by yuyuya090908** [comment]
所以怎么弄啊

**Comment by MovTery** [comment]
@yuyuya090908  启动器同步了Pojav的有关全屏的代码，但是部分系统没法用，所以我退回了，发了个紧急修复，更新一下就好了

**Comment by yuyuya090908** [comment]
感谢

MovTery ***@***.***> 于 2024年12月31日周二 下午4:06写道：
